[package]
name = "eamon_domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.0"
config = "0.13.3"
dotenv = "0.15.0"
sqlx = { version = "0.7.1", features = ["postgres"] }
